### ISSUE TITLE
tcp fit in linux

### ISSUE THREAD

**Issue by madhanraj** [SpyrosMArtel/TCP-Fit-Illinois#1]
have you ever tried tcp fit implementation in linux (kernel C) ? If so can you please share the code or link

**Comment by SpyrosMArtel** [comment]
Hello madhanraj,

I have not tried the implementation (it was mainly for my thesis) in linux kernel, and at the time of writing I do not think there is one. I came across a debian forum (if I recall), where there was a suggestion to implement and include TCP-FIT in the kernel, of which I have not kept the link.

Feel free to contact me again, should you have any further questions. Have fun!

**Comment by madhanraj** [comment]
Hi Spyros, 
I am also working on research of same . I tried implementing for linux . The value of Beta in your code is always some constant . Was it added to make it more aggressive to test?

**Comment by SpyrosMArtel** [comment]
Hello madhanraj,
Regarding TCP-Fit and according to the relevant paper (http://www.tcpengines.com/wp-content/uploads/2013/11/tcp-whitepaper.pdf, page 8), it mentions the following about the beta in the code:

_"For some specific scenarios that require a faster response speed, the users can modify the N updating function as (__a different N formula__) ... and increase beta to raise the step length of N increases. Figure 3 plots the response speed of TCP-FIT with different settings."_

For this reason, it was decided, for completeness, to add this formula and some logic to change the formula used depending on the value of this variable (0, for do not use the new formula, >0, otherwise). To answer the question, the beta value along with the new formula does make the algorithm more aggressive by increasing its responce.

Furthermore, the BETA_VALUE constant was created for convenience. In other words, it was easier to manipulate a constant (and re-compile), instead of hunting down the beta variable to change its value.

**Comment by madhanraj** [comment]
Thanks for you reply . I am testing the fairness but still it fit is not upto the mark . Please update if you find more . 

Btw have a look at this paper 
http://ieeexplore.ieee.org/xpl/articleDetails.jsp?arnumber=7128680&sortType%3Dasc_p_Sequence%26filter%3DAND(p_Publication_Number%3A4234)%26pageNumber%3D4%26rowsPerPage%3D75

It might be useful for your research

**Comment by madhanraj** [comment]
Hi Spyros,
Did u try NS3 implementation of the same ? Can you please add the NS3 implementation in our github . It would be of great help for my research.

Regards,
Madhan

**Comment by SpyrosMArtel** [comment]
Hi Madhan,

Really sorry for the late reply, there where really busy days. Nevertheless, I am not aware of the NS3 implementation, as it sounds like something new and I have already finished my research.

I would really like to help out and add the NS3 implementation in github. but I am keeping this repository for the university, and anyone interested in browsing the implementation after reading my thesis (publishing is pending). Hence, I think it would be better if I keep it clean.

Regards,
Spyros
